name: Python Tests and Linting

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests.py
      