name: Weekly stable build and release

on:
  schedule:
    cron: "0 2 * * 2"

jobs:
  build:
    name: Create Stable Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: stable-tag-${{ steps.date.outputs.date }}
          release_name: stable-release-${{ steps.date.outputs.date }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: true
